### ISSUE TITLE
Is there a way to manipulate this to just send a keycode over bluetooth?

### ISSUE THREAD

**Issue by vwmofo** [ruundii/bthidhub#51] opened 2022-09-14 18:21 UTC
I'm trying to use this as a method to control a firestick utilizing a Flirc USB.  The idea is to use trigger happy to capture the key events from my remote control and then tell bthidhub to send the commands across to the firestick.

Thanks in advance!

**Comment by Dreamsorcerer** [comment] 2022-09-15 13:52
Duplicate of #50. As mentioned there, if you can hack around with a bit of Python, then you should be able to figure it out. If not, then I'm afraid you're out of luck.

**Closed as completed by Dreamsorcerer** 2022-09-15 13:52 UTC

**Comment by vwmofo** [comment] 2022-09-15 14:04
I'm sure I could figure it out but I need to know what I should be interacting with in this project.  Ie what is responsible for sending the keypresses to BT and does hid_devices.py take command line arguments.  Also the instructions for creating a filter really could use some more simplification.  For example the Flirc USB is designed to appear as a standard keyboard but doesn't work unless I use it in compatibility mode.  I'd love to try to figure out how to write a filter, but as the instructions only reference a mouse and that's zero help to me.
